spring:
  datasource:
#    include:
#      - h2
#      - postgre
#      - oauth
#      - security
  mvc:
    hiddenmethod:
        filter:
          enabled: true


  main:
    allow-circular-references: true
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
       registration:
          google:
            scope:
              - profile
              - email

logging:
  level:
    org:
      hibernate:
        type:
          sql: DEBUG
          descriptor:
            sql: DEBUG